name: Build Release Images

on:
 schedule:
    - cron: '0 0 1 * *'
 workflow_dispatch:
  inputs:
   sure:
         description: 'Are you sure you want to trigger this Workflow?'
         required: true
         default: 'no'
         type: choice
         options:
         - yes
         - no
jobs:
 build_backend:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write
   steps:
   - uses: actions/checkout@v3 
   - uses: gacts/install-podman@v1
   
   - name: Check Podman Version
     run: podman version
   
   - name: Podman Sign in
     run: podman login -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}} ghcr.io
   
   - name: Build Container
     run: podman build --tag wiz_app_backend:$(date +%y%m) --file Dockerfile.backend --layers --cache-from ghcr.io/wellcome-leap-sheffield/wiz_app_backend --cache-to ghcr.io/wellcome-leap-sheffield/wiz_app_backend --cache-ttl 30000h
   
   - name: Push Container to Github Containers
     run: podman push wiz_app_backend:$(date +%y%m) docker://ghcr.io/wellcome-leap-sheffield/wiz_app_backend:latest 
 build_frontend:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write
   steps:
   - uses: actions/checkout@v3 
   - uses: gacts/install-podman@v1
   
   - name: Check Podman Version
     run: podman version
   
   - name: Podman Sign in
     run: podman login -u ${{ github.actor }} -p ${{secrets.GITHUB_TOKEN}} ghcr.io
   
   - name: Build Container
     run: podman build --tag wiz_app_frontend:$(date +%y%m) --file Dockerfile.frontend --layers --cache-from ghcr.io/wellcome-leap-sheffield/wiz_app_frontend --cache-to ghcr.io/wellcome-leap-sheffield/wiz_app_frontend --cache-ttl 30000h
   
   - name: Push Container to Github Containers
     run: podman push wiz_app_frontend:$(date +%y%m) docker://ghcr.io/wellcome-leap-sheffield/wiz_app_frontend:latest 
