FROM python:3.12-slim

WORKDIR /app


COPY . .

RUN pip install --no-cache-dir -U pip \
    && pip install --no-cache-dir .

# Expose to run as a web service
EXPOSE 8000


CMD ["uvicorn", "ai_agent.main:app", "--host", "0.0.0.0", "--port", "8000"]
